### ISSUE TITLE
Plugin does not initialize in Purpur/Paper 1.21.1

### ISSUE THREAD

**Issue by Brasil150** [Kikisito/GoldenHeads#17]
Hello, GoldenHeads 2.1 plugin is not initializing in Purpur/Paper 1.21. Plugin generates the following logs in the console:
Server version: Purpur 1.21.1-2308-8332fa4 (MC: 1.21.1)

```
[18:56:32 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'goldenheads-2.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/google/inject/Key
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:129) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:560) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: com/google/inject/Key
        at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:529) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:508) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        ... 9 more
Caused by: java.lang.ClassNotFoundException: com.google.inject.Key
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:199) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:166) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:529) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:508) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        ... 9 more
```

```
[18:42:56 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'goldenheads-2.1.jar' in folder 'plugins/.paper-remapped'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/google/inject/Key
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:129) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:560) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: com/google/inject/Key
        at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:529) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:508) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
        ... 9 more
Caused by: java.lang.ClassNotFoundException: com.google.inject.Key
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:199) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:166) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:529) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:508) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
        ... 9 more
```

**Comment by Reddishye** [comment]
@Kikisito u made a build instead of a shadow jar?

**Comment by Kikisito** [comment]
I may have uploaded the wrong jar, please try again with the latest one

https://github.com/Kikisito/GoldenHeads/releases/tag/2.1

**Comment by Reddishye** [comment]
@Brasil150 I tested the new jar and works good for me. Check it out!

**Comment by Brasil150** [comment]
Where can I find it?

**Comment by Kikisito** [comment]
Seems to work fine. I'm closing the issue. Sorry for the inconvenience.

**Comment by Brasil150** [comment]
Hello, sorry but I think it will have to be opened again. The plugin still does not initialize.

```
[19:49:06 INFO]: [GoldenHeads] Enabling GoldenHeads v2.1
[19:49:06 INFO]: [GoldenHeads] Thanks for using GoldenHeads v2.1 by Kikisito.
[19:49:06 ERROR]: Error occurred while enabling GoldenHeads v2.1 (Is it up to date?)
java.lang.IllegalArgumentException: Can not set net.minecraft.world.item.component.ResolvableProfile field org.bukkit.craftbukkit.inventory.CraftMetaSkull.profile to com.mojang.authlib.GameProfile
        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:228) ~[?:?]
        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:232) ~[?:?]
        at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:115) ~[?:?]
        at java.base/java.lang.reflect.Field.set(Field.java:836) ~[?:?]
        at goldenheads-2.1.jar/com.github.kikisito.goldenheads.GoldenHead.base64SkullBuilder(GoldenHead.java:105) ~[goldenheads-2.1.jar:?]
        at goldenheads-2.1.jar/com.github.kikisito.goldenheads.GoldenHead.createHead(GoldenHead.java:69) ~[goldenheads-2.1.jar:?]
        at goldenheads-2.1.jar/com.github.kikisito.goldenheads.Main.registerRecipe(Main.java:90) ~[goldenheads-2.1.jar:?]
        at goldenheads-2.1.jar/com.github.kikisito.goldenheads.Main.onEnable(Main.java:59) ~[goldenheads-2.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:758) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:520) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:366) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[19:49:06 INFO]: [GoldenHeads] Disabling GoldenHeads v2.1
```

**Comment by Kikisito** [comment]
This is a different issue now, let's discuss about it in #18
