### ISSUE TITLE
[19:16:46 ERROR]: Error occurred while enabling GoldenHeads v2.1 (Is it up to date?)

### ISSUE THREAD

**Issue by TymekSL** [Kikisito/GoldenHeads#19]
[19:16:46 ERROR]: Error occurred while enabling GoldenHeads v2.1 (Is it up to date?)
java.lang.IllegalArgumentException: Can not set net.minecraft.world.item.component.ResolvableProfile field org.bukkit.craftbukkit.inventory.CraftMetaSkull.profile to com.mojang.authlib.GameProfile
        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:228) ~[?:?]
        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:232) ~[?:?]
        at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:115) ~[?:?]
        at java.base/java.lang.reflect.Field.set(Field.java:836) ~[?:?]
        at goldenheads-2.1.jar/com.github.kikisito.goldenheads.GoldenHead.base64SkullBuilder(GoldenHead.java:105) ~[goldenheads-2.1.jar:?]
        at goldenheads-2.1.jar/com.github.kikisito.goldenheads.GoldenHead.createHead(GoldenHead.java:69) ~[goldenheads-2.1.jar:?]
        at goldenheads-2.1.jar/com.github.kikisito.goldenheads.Main.registerRecipe(Main.java:90) ~[goldenheads-2.1.jar:?]
        at goldenheads-2.1.jar/com.github.kikisito.goldenheads.Main.onEnable(Main.java:59) ~[goldenheads-2.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[19:16:46 INFO]: [GoldenHeads] Disabling GoldenHeads v2.1
[19:16:46 INFO]: [MobMoney] Enabling MobMoney v5.1.8

**Comment by Kikisito** [comment]
Duplicate #18

**Comment by TymekSL** [comment]
> Duplicate #18

you are blind? using paper spigot, he using purpur

**Comment by Kikisito** [comment]
> > Duplicate #18
> 
> you are blind? using paper spigot, he using purpur

all of these are trying to be solved in #18. please don't answer again if you are going to disrespect me
