### ISSUE TITLE
your fantastic stupid plugin still wont work pseudo developer XDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD

### ISSUE THREAD

**Issue by TymonLC** [Kikisito/GoldenHeads#20]
[10:03:37] [Server thread/INFO]: [GoldenHeads] Thanks for using GoldenHeads v2.2 by Kikisito.
[10:03:37] [Server thread/ERROR]: Error occurred while enabling GoldenHeads v2.2 (Is it up to date?)
java.lang.IllegalArgumentException: Invalid texture url: e3RleHR1cmVzOntTS0lOOnt1cmw6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2ZkMjdkOGIyMThiNWFhOTcyZmRhOTA1NDkyNmQ3YjFiMmMwMzI5YTQ1NjMzMjE0OGZjYzNkNmM2ZDM0Y2YwZiJ9fX0=
	at goldenheads-2.2.jar/com.github.kikisito.goldenheads.GoldenHead.skullBuilder(GoldenHead.java:112) ~[goldenheads-2.2.jar:?]
	at goldenheads-2.2.jar/com.github.kikisito.goldenheads.GoldenHead.createHead(GoldenHead.java:73) ~[goldenheads-2.2.jar:?]
	at goldenheads-2.2.jar/com.github.kikisito.goldenheads.Main.registerRecipe(Main.java:90) ~[goldenheads-2.2.jar:?]
	at goldenheads-2.2.jar/com.github.kikisito.goldenheads.Main.onEnable(Main.java:59) ~[goldenheads-2.2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:641) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:590) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[10:03:37] [Server thread/INFO]: [GoldenHeads] Disabling GoldenHeads v2.2

**Comment by Kikisito** [comment]
then don't use it
